name: Check BPF Packages

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Clone source
        run: |
          git clone https://github.com/padavanonly/immortalwrt-mt798x-6.6 openwrt

      - name: Update feeds
        working-directory: openwrt
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Check package exists
        working-directory: openwrt
        run: |
          echo "===== CHECK PACKAGE ====="

          grep -R "KernelPackage/sched-bpf" package feeds target || true

          grep -R "KernelPackage/xdp-sockets-diag" package feeds target || true

          echo "===== CHECK KCONFIG ====="

          grep -R "XDP_SOCKETS" package feeds target || true
